variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - build
  - test
  
compile_atlas:
  stage: build
  image: atlas/analysisbase:21.2.64
  tags:
    - cvmfs
  script:
    - source /home/atlas/release_setup.sh
    - mkdir build
    - cd build
    - cmake ..
    - make    
  artifacts:
    paths:
      - build

compile_standalone:
  stage: build
  image: rootproject/root-ubuntu16  
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build    

test_atlas:
  stage: test
  image: atlas/analysisbase:21.2.64
  tags:
    - cvmfs
  dependencies:
    - compile_atlas    
  script:
    - source /home/atlas/release_setup.sh
    - cd build
    - ctest

test_standalone:
  stage: test
  image: rootproject/root-ubuntu16  
  dependencies:
    - compile_standalone    
  script:
    - cd build
    - ctest    

    
